const {
    DISCORD_TOKEN,
    TILTIFY_ACCESS_TOKEN,
    DONATION_REFRESH,
    MONGO_URL
} = process.env

module.exports={
    DISCORD_TOKEN: DISCORD_TOKEN || '',
    TILTIFY_ACCESS_TOKEN: TILTIFY_ACCESS_TOKEN || '',
    DONATION_REFRESH: !!Number(DONATION_REFRESH) || 30000,
    MONGO_URL: MONGO_URL || ''
}